-- 
-- Database structure
--

ALTER DATABASE __DATABASE__ CHARACTER SET = __CHARACTER__ COLLATE = __COLLATE__;

--
-- Table structure for table `auth`
--

DROP TABLE IF EXISTS `auth`;
CREATE TABLE `auth` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `selector` char(12) COLLATE __COLLATE__ NOT NULL,
  `token` char(128) COLLATE __COLLATE__ NOT NULL,
  `userid` int(10) UNSIGNED NOT NULL,
  `expires` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `selector` (`selector`)
) ENGINE=InnoDB DEFAULT CHARSET=__CHARACTER__ COLLATE=__COLLATE__;

--
-- Table structure for table `movies`
--

ALTER TABLE `movies`
  CONVERT TO CHARACTER SET __CHARACTER__ COLLATE __COLLATE__,
  CHANGE `imdbid` `imdbid`  VARCHAR(20) CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `name` `name`  VARCHAR(255) CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `aka` `aka`  TEXT CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `languages` `languages` TEXT CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `country` `country` TEXT CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `genres` `genres` TEXT CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `director` `director` TEXT CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `writer` `writer` TEXT CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `producer` `producer` TEXT CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `music` `music` TEXT CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `cast` `cast` TEXT CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `taglines` `taglines` TEXT CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `plotoutline` `plotoutline` TEXT CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `plots` `plots` TEXT CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `format` `format`  VARCHAR(32) CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `notes` `notes` TEXT CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `loanname` `loanname`  VARCHAR(100) CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `trailer` `trailer`  VARCHAR(255) CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `subtitles` `subtitles`  VARCHAR(255) CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `audio` `audio`  VARCHAR(255) CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `video` `video` VARCHAR(255) CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  DROP INDEX `search`,
  ENGINE=InnoDB;

--
-- Table structure for table `users`
--

ALTER TABLE `users`
  CONVERT TO CHARACTER SET __CHARACTER__ COLLATE __COLLATE__,
  CHANGE `email` `email` VARCHAR(191) CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `username` `username` VARCHAR(50) CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  CHANGE `password` `password` VARCHAR(255) CHARACTER SET __CHARACTER__ COLLATE __COLLATE__ NOT NULL,
  ENGINE=InnoDB;
